<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TagsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tags')->delete();
        
        \DB::table('tags')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'ប្រភេទឯកសារ',
                'desp' => 'ប្រភេទឯកសារផ្លូវការរបស់ព្រះរាជាណាចក្រកម្ពុជា។',
                'tpid' => "",
                'pid' => NULL,
                'model' => 'App\\Models\\Document\\Tag\\Type',
                'cids' => NULL,
                'image' => '',
                'record_index' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ព្រះរាជក្រម',
                'desp' => 'ព្រះរាជក្រម',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ព្រះរាជក្រឹត្យ.បក',
                'desp' => 'ព្រះរាជក្រឹត្យ.បក',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'អនុក្រឹត្យ.បក',
                'desp' => 'អនុក្រឹត្យ.បក',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ព្រះរាជក្រឹត្យ.តត',
                'desp' => 'ព្រះរាជក្រឹត្យ.តត',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'អនុក្រឹត្យ.តត',
                'desp' => 'អនុក្រឹត្យ.តត',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'សជណ',
                'desp' => 'សជណ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'សេចក្ដីសម្រេច',
                'desp' => 'សេចក្ដីសម្រេច',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'សារាចរ និង សារាចរណែនាំ',
                'desp' => 'សារាចរ និង សារាចរណែនាំ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ប្រកាស',
                'desp' => 'ប្រកាស',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'គោលនយោបាយជាតិ',
                'desp' => 'គោលនយោបាយជាតិ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'ផែនការយុទ្ធសាស្ត្រ',
                'desp' => 'ផែនការយុទ្ធសាស្ត្រ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'បទបញ្ជារាជរដ្ឋាភិបាល',
                'desp' => 'បទបញ្ជារាជរដ្ឋាភិបាល',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'ផែនការសកម្មភាពក្រសួងនានា',
                'desp' => 'ផែនការសកម្មភាពក្រសួងនានា',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'ផែនការសកម្មភាពក្រសួងនានា',
                'desp' => 'ផែនការសកម្មភាពក្រសួងនានា',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'របាយការណ៍ប្រចាំថ្ងៃ',
                'desp' => 'របាយការណ៍ប្រចាំថ្ងៃ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'របាយការណ៍ប្រចាំខែ',
                'desp' => 'របាយការណ៍ប្រចាំខែ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'របាយការណ៍ការប្រចាំឆ្នាំ',
                'desp' => 'របាយការណ៍ការប្រចាំឆ្នាំ',
                'tpid' => "1",
                'pid' => 1,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ឈ្មោះហត្ថលេខា',
                'desp' => 'ឈ្មោះថ្នាក់ដឹកនាំដែលបានចុះហត្ថលេខាលើឯកសារ',
                'tpid' => "",
                'pid' => NULL,
                'model' => 'App\\Models\\Document\\Tag\\Signature',
                'cids' => NULL,
                'image' => '',
                'record_index' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ហ៊ុន សែន',
                'desp' => 'ហ៊ុន សែន',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'ជា ស៊ីម',
                'desp' => 'ជា ស៊ីម',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'ហេង សំរិន',
                'desp' => 'ហេង សំរិន',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'សាយ ឈុំ',
                'desp' => 'សាយ ឈុំ',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ត្រាំ អ៊ីវតឹក',
                'desp' => 'ត្រាំ អ៊ីវតឹក',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ជា សុផារ៉ា',
                'desp' => 'ជា សុផារ៉ា',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ស៊ុន ចាន់ថុល',
                'desp' => 'ស៊ុន ចាន់ថុល',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ជា វ៉ាន់ដេត',
                'desp' => 'ជា វ៉ាន់ដេត',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'សាយ សំអាល់',
                'desp' => 'សាយ សំអាល់',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ទៀ បាញ់',
                'desp' => 'ទៀ បាញ់',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ស ខេង',
                'desp' => 'ស ខេង',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'ម៉ែន សំអន',
                'desp' => 'ម៉ែន សំអន',
                'tpid' => "19",
                'pid' => 19,
                'model' => '',
                'cids' => NULL,
                'image' => '',
                'record_index' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'name' => 'ក្រសួងការពារជាតិ',
                'desp' => 'ឯកឧត្តម ទៀ សីហា',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 3,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:33:57',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 47,
                'name' => 'អគ្គនាយកដ្ឋានសម្របសម្រួលកិច្ចការទូទៅ',
                'desp' => 'មានភារកិច្ចក្នុងការ រៀបចំទាំងមូលកិច្ចការទូទៅ',
                'tpid' => "32:33",
                'pid' => 33,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 07:28:47',
                'updated_at' => '2023-09-04 07:28:47',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'ក្រសួងមហាផ្ទៃ',
                'desp' => 'ឯកឧត្តម ស សុខា',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 2,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:33:50',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 46,
                'name' => 'អគ្គនាយកដ្ឋាន កិច្ចប្រជុំ',
                'desp' => 'អគ្គនាយកដ្ឋាន កិច្ចប្រជុំ',
                'tpid' => "32:33",
                'pid' => 33,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 07:02:36',
                'updated_at' => '2023-09-04 07:33:36',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 39,
                'name' => 'ក្រសួងអភិវឌ្ឍន័ជនបទ',
                'desp' => 'ឯកឧត្តម ឆាយ ប្ញទ្ធីសែន',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 7,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:11',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 40,
                'name' => 'ក្រសួងពាណិជ្ជកម្ម',
                'desp' => 'លោកជំទាវ ចម និម្មល',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 8,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:14',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 43,
                'name' => 'ក្រសួងផែនការ',
                'desp' => 'ឯកឧត្តម ប៊ិន ត្រឈៃ',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 11,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:29',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 42,
                'name' => 'ក្រសួង រ៉ែ និងថាមពល',
                'desp' => 'ឯកឧត្តម កែវ រតនៈ',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 10,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:24',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 44,
                'name' => 'ក្រសួងអប់រំ យុវជន និងកីឡា',
                'desp' => 'ឯកឧត្តម ហង់ជួន ណារ៉ុន',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 12,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:33',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 32,
                'name' => 'រាជរដ្ឋាភិបាល',
                'desp' => 'សម្ដេចមហាបរវធិបតី ហ៊ុន ម៉ាណែត',
                'tpid' => "",
                'pid' => NULL,
                'model' => 'App\\Models\\Document\\Tag\\Organization',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:36:57',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 33,
                'name' => 'ទីស្ដីការគណៈរដ្ឋមន្ត្រី',
                'desp' => 'ឯកឧត្តម វង្សី វិស្សុត',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:33:02',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 38,
                'name' => 'ក្រសួងកសិកម្ម រក្ខាប្រមាញ់ និងនេសាទ',
                'desp' => 'ឯកឧត្តម ឌិត ទីណា',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 6,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:07',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 36,
                'name' => 'ក្រសួងការបរទេស និងសហប្រតិបត្តិការអន្តរជាតិ',
                'desp' => 'ឯកឧត្តម សុខ ចិន្តាសោភា',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 4,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:33:41',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 48,
                'name' => 'អគ្គនាយកដ្ឋាន រៀបចំឯកសារ',
                'desp' => 'អគ្គនាយកដ្ឋាន រៀបចំឯកសារ',
                'tpid' => "32:33",
                'pid' => 33,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 07:29:06',
                'updated_at' => '2023-09-04 07:32:45',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 58,
                'name' => 'ក្រសួងសាធារណការ និងដឹកជញ្ជូន',
                'desp' => 'ឯកឧត្តម ប៉េង ពោធិ៍នា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:26:09',
                'updated_at' => '2023-09-04 08:35:43',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 53,
                'name' => 'ក្រសួងព័ត៌មាន',
                'desp' => 'ក្រសួងព័ត៌មាន។ ឯកឧត្តម នេត្រ ភក្ត្រា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:23:25',
                'updated_at' => '2023-09-04 08:23:25',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 54,
                'name' => 'ក្រសួងយុត្តិធម៌',
                'desp' => 'ក្រសួងយុត្តិធម៌។ ឯកឧត្តម កើត រិទ្ធ',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:23:46',
                'updated_at' => '2023-09-04 08:23:46',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 37,
                'name' => 'ក្រសួងសេដ្ឋកិច្ច និងហិរញ្ញវត្ថុ',
                'desp' => 'ឯកឧត្តម អូន ព័ន្ធមុនីរ័ត្ន',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 5,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:02',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 41,
                'name' => 'ក្រសួងឧស្សាហកម្ម វិទ្យាសាស្ត្រ បច្ចេកវិទ្យា និងនវានុវត្ដន៍',
                'desp' => 'ឯកឧត្តម ហែម វណ្ណឌី',
                'tpid' => "32",
                'pid' => 32,
                'model' => '',
                'cids' => NULL,
                'image' => NULL,
                'record_index' => 9,
                'created_at' => NULL,
                'updated_at' => '2023-09-04 08:34:19',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 50,
                'name' => 'ក្រសួងរៀបចំដែនដី នគរូបនីយកម្ម និងសំណង់',
                'desp' => 'ឯកឧត្តម សាយ សំអាល់',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:16:16',
                'updated_at' => '2023-09-04 08:34:39',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 59,
                'name' => 'ក្រសួងវប្បធម៌ និងវិចិត្រសិល្បៈ',
                'desp' => 'លោកជំទាវ ភឿង សកុណា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:26:49',
                'updated_at' => '2023-09-04 08:34:45',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 60,
                'name' => 'ក្រសួងទេសចរណ៍',
                'desp' => 'ឯកឧត្តម សុខ សូកេន',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:27:12',
                'updated_at' => '2023-09-04 08:34:51',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 61,
                'name' => 'ក្រសួងធម្មការ និងសាសនា',
                'desp' => 'ឯកឧត្តម ចាយ បូរិន',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:27:52',
                'updated_at' => '2023-09-04 08:34:56',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 62,
                'name' => 'ក្រសួងកិច្ចការនារី',
                'desp' => 'លោកជំទាវ អ៉ឹង កន្ថាផាវី',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:28:20',
                'updated_at' => '2023-09-04 08:35:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 63,
                'name' => 'ក្រសួងការងារ និងបណ្ដុះបណ្ដាលវិជ្ជាជីវៈ',
                'desp' => 'ឯកឧត្តម ហេង សួរ',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:28:58',
                'updated_at' => '2023-09-04 08:35:05',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 64,
                'name' => 'ក្រសួងមុខងារសាធារណៈ',
                'desp' => 'ឯកឧត្តម ហ៊ុន ម៉ានី',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:29:28',
                'updated_at' => '2023-09-04 08:35:08',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 65,
                'name' => 'រដ្ឋលេខាធិការដ្ឋានអាកាសចរស៊ីវិល',
                'desp' => 'ឯកឧត្តម ម៉ៅ ហាវណ្ណាល់',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:30:10',
                'updated_at' => '2023-09-04 08:35:12',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 66,
                'name' => 'រដ្ឋលេខាធិការដ្ឋានកិច្ចការព្រំដែន',
                'desp' => 'ឯកឧត្តម ឡាំ ជា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:30:38',
                'updated_at' => '2023-09-04 08:35:16',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 49,
                'name' => 'ក្រសួងសង្គមកិច្ច អតីតយុទ្ធជន និង យវនីតិសម្បទា',
                'desp' => 'ឯកឧត្តម ជា សុមេធី',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:08:53',
                'updated_at' => '2023-09-04 08:35:21',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 51,
                'name' => 'ក្រសួងបរិស្ថាន',
                'desp' => 'ឯកឧត្តម អ៊ាង សុផល្លែត',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:19:56',
                'updated_at' => '2023-09-04 08:35:27',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 52,
                'name' => 'ក្រសួងធនធានទឹក និងឧតុនិយម',
                'desp' => 'ឯកឧត្តម ថោ ជេដ្ឋា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:22:30',
                'updated_at' => '2023-09-04 08:35:34',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 56,
                'name' => 'ក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍',
                'desp' => 'ឯកឧត្តម ជា វ៉ាន់ដេត',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:25:04',
                'updated_at' => '2023-09-04 08:35:38',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 57,
                'name' => 'ក្រសួងសុខភិបាល',
                'desp' => 'ឯកឧត្តម ឈាង រ៉ា',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:25:23',
                'updated_at' => '2023-09-04 08:35:47',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 55,
                'name' => 'ក្រសួងអធិការកិច្ច',
                'desp' => 'ឯកឧត្តម ហួត ហាក់',
                'tpid' => "32",
                'pid' => 32,
                'model' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'created_at' => '2023-09-04 08:24:27',
                'updated_at' => '2023-09-04 08:35:53',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}