<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;

class UnitTeamworkRegulatorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unit_teamwork_regulators')->delete();
        
        \DB::table('unit_teamwork_regulators')->insert(array (
            0 => 
            array (
                'id' => 2,
                'document_id' => 45982,
                'unit_teamwork_type_id' => 4,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'document_id' => 45977,
                'unit_teamwork_type_id' => 5,
                'ministry_id' => 12,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:59:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'document_id' => 45837,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'document_id' => 45758,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'document_id' => 45668,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:11:18',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'document_id' => 45339,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 12,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:15:11',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'document_id' => 20477,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'document_id' => 20476,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 43,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:15:59',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'document_id' => 20293,
                'unit_teamwork_type_id' => 17,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'document_id' => 20131,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'document_id' => 18657,
                'unit_teamwork_type_id' => 9,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'document_id' => 18540,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => 11,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:02:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'document_id' => 18384,
                'unit_teamwork_type_id' => 9,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'document_id' => 18305,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => 12,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:03:52',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'document_id' => 18211,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'document_id' => 17918,
                'unit_teamwork_type_id' => 9,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'document_id' => 17873,
                'unit_teamwork_type_id' => 18,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'document_id' => 17706,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'document_id' => 17243,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'document_id' => 17223,
                'unit_teamwork_type_id' => 15,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'document_id' => 17202,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'document_id' => 17114,
                'unit_teamwork_type_id' => 10,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'document_id' => 15885,
                'unit_teamwork_type_id' => 11,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'document_id' => 14753,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'document_id' => 13593,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'document_id' => 13548,
                'unit_teamwork_type_id' => 19,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'document_id' => 45936,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'document_id' => 45933,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'document_id' => 45855,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'document_id' => 45932,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'document_id' => 45854,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'document_id' => 45852,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'document_id' => 45785,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'document_id' => 45784,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'document_id' => 45782,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'document_id' => 45544,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'document_id' => 45432,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'document_id' => 45391,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'document_id' => 45378,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'document_id' => 45372,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'document_id' => 45368,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'document_id' => 45367,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'document_id' => 45364,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'document_id' => 45310,
                'unit_teamwork_type_id' => 20,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'document_id' => 45258,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'document_id' => 45257,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'document_id' => 45256,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'document_id' => 45254,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'document_id' => 45249,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'document_id' => 45223,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'document_id' => 20503,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'document_id' => 20500,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'document_id' => 20499,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'document_id' => 20497,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'document_id' => 20474,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'document_id' => 20450,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 58,
                'document_id' => 20449,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 59,
                'document_id' => 20446,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 60,
                'document_id' => 20297,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 61,
                'document_id' => 20262,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 62,
                'document_id' => 20261,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 63,
                'document_id' => 20260,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'document_id' => 20258,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'document_id' => 20250,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 66,
                'document_id' => 20207,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'document_id' => 20206,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'document_id' => 20193,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'document_id' => 20164,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'document_id' => 20153,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 71,
                'document_id' => 20144,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 72,
                'document_id' => 20137,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 73,
                'document_id' => 20127,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 74,
                'document_id' => 20125,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 75,
                'document_id' => 20124,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 76,
                'document_id' => 20115,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 77,
                'document_id' => 20102,
                'unit_teamwork_type_id' => 1,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 78,
                'document_id' => 20102,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 79,
                'document_id' => 20097,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 80,
                'document_id' => 20005,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 81,
                'document_id' => 19982,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 82,
                'document_id' => 19954,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 83,
                'document_id' => 19823,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 84,
                'document_id' => 19582,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 85,
                'document_id' => 19617,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 86,
                'document_id' => 19646,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 87,
                'document_id' => 19799,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 88,
                'document_id' => 19822,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 89,
                'document_id' => 18570,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 90,
                'document_id' => 18548,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 91,
                'document_id' => 18547,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 92,
                'document_id' => 18541,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 93,
                'document_id' => 18534,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 94,
                'document_id' => 18530,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 95,
                'document_id' => 18528,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 96,
                'document_id' => 18515,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 97,
                'document_id' => 18514,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 98,
                'document_id' => 18489,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 99,
                'document_id' => 18485,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 100,
                'document_id' => 18477,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 101,
                'document_id' => 18471,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 102,
                'document_id' => 18446,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 103,
                'document_id' => 18445,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 104,
                'document_id' => 18408,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 105,
                'document_id' => 18407,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 106,
                'document_id' => 17864,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 107,
                'document_id' => 17306,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 108,
                'document_id' => 17075,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 109,
                'document_id' => 17045,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 110,
                'document_id' => 17037,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 111,
                'document_id' => 16918,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 112,
                'document_id' => 16466,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 113,
                'document_id' => 16465,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 114,
                'document_id' => 16464,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 115,
                'document_id' => 16446,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 116,
                'document_id' => 16441,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 117,
                'document_id' => 16321,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 118,
                'document_id' => 15952,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 119,
                'document_id' => 15913,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 120,
                'document_id' => 15907,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 121,
                'document_id' => 15882,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 122,
                'document_id' => 15876,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 123,
                'document_id' => 15870,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 124,
                'document_id' => 15868,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 125,
                'document_id' => 14899,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 126,
                'document_id' => 14883,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 127,
                'document_id' => 14858,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 128,
                'document_id' => 14779,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 129,
                'document_id' => 14768,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 130,
                'document_id' => 14756,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 131,
                'document_id' => 14722,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 132,
                'document_id' => 14213,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 133,
                'document_id' => 14094,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 134,
                'document_id' => 14008,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 135,
                'document_id' => 13977,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 136,
                'document_id' => 13923,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 137,
                'document_id' => 13912,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 138,
                'document_id' => 13882,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 139,
                'document_id' => 13880,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 140,
                'document_id' => 13827,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 141,
                'document_id' => 13825,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 142,
                'document_id' => 13813,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 143,
                'document_id' => 13802,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 144,
                'document_id' => 13779,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 145,
                'document_id' => 13622,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 146,
                'document_id' => 13585,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 147,
                'document_id' => 13563,
                'unit_teamwork_type_id' => 3,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 148,
                'document_id' => 13513,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 149,
                'document_id' => 13417,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 150,
                'document_id' => 13401,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 151,
                'document_id' => 13399,
                'unit_teamwork_type_id' => 6,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 152,
                'document_id' => 10672,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 153,
                'document_id' => 9328,
                'unit_teamwork_type_id' => 14,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 154,
                'document_id' => 20195,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => 42,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:05:16',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 155,
                'document_id' => 18762,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:38:51',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 156,
                'document_id' => 18545,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => 46,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:06:10',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 157,
                'document_id' => 18527,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:06:49',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 158,
                'document_id' => 18518,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 2,
                'creation' => 0,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 09:58:07',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 159,
                'document_id' => 18457,
                'unit_teamwork_type_id' => 13,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 160,
                'document_id' => 18416,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 161,
                'document_id' => 17714,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 34,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:47:52',
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 162,
                'document_id' => 17142,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 163,
                'document_id' => 15976,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 53,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:33:22',
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 164,
                'document_id' => 15975,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 288,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:49:49',
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 165,
                'document_id' => 14903,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 10,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:51:42',
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 166,
                'document_id' => 14771,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 167,
                'document_id' => 13641,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 39,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:52:34',
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 168,
                'document_id' => 13414,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 169,
                'document_id' => 13258,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 10:55:35',
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 170,
                'document_id' => 18673,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:18:32',
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 171,
                'document_id' => 18672,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:18:48',
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 172,
                'document_id' => 18671,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:20:18',
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 173,
                'document_id' => 17797,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-04-20 11:20:56',
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 174,
                'document_id' => 17795,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 175,
                'document_id' => 17794,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 176,
                'document_id' => 17792,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 177,
                'document_id' => 17791,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 178,
                'document_id' => 17772,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 179,
                'document_id' => 17771,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 180,
                'document_id' => 17770,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            179 => 
            array (
                'id' => 181,
                'document_id' => 17769,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            180 => 
            array (
                'id' => 182,
                'document_id' => 17768,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            181 => 
            array (
                'id' => 183,
                'document_id' => 17767,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            182 => 
            array (
                'id' => 184,
                'document_id' => 17766,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            183 => 
            array (
                'id' => 185,
                'document_id' => 17756,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            184 => 
            array (
                'id' => 186,
                'document_id' => 17755,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            185 => 
            array (
                'id' => 187,
                'document_id' => 17754,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            186 => 
            array (
                'id' => 188,
                'document_id' => 17753,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            187 => 
            array (
                'id' => 189,
                'document_id' => 17752,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            188 => 
            array (
                'id' => 190,
                'document_id' => 17751,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            189 => 
            array (
                'id' => 191,
                'document_id' => 17749,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            190 => 
            array (
                'id' => 192,
                'document_id' => 17748,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            191 => 
            array (
                'id' => 193,
                'document_id' => 17747,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            192 => 
            array (
                'id' => 194,
                'document_id' => 17746,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            193 => 
            array (
                'id' => 195,
                'document_id' => 17745,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            194 => 
            array (
                'id' => 196,
                'document_id' => 17744,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            195 => 
            array (
                'id' => 197,
                'document_id' => 17743,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            196 => 
            array (
                'id' => 198,
                'document_id' => 17742,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            197 => 
            array (
                'id' => 199,
                'document_id' => 13350,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            198 => 
            array (
                'id' => 200,
                'document_id' => 13346,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            199 => 
            array (
                'id' => 201,
                'document_id' => 13343,
                'unit_teamwork_type_id' => 7,
                'ministry_id' => NULL,
                'creation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            200 => 
            array (
                'id' => 202,
                'document_id' => 18451,
                'unit_teamwork_type_id' => 21,
                'ministry_id' => 2,
                'creation' => 1,
                'created_at' => '2018-04-20 10:24:42',
                'updated_at' => '2018-04-20 10:24:42',
                'deleted_at' => NULL,
            ),
            201 => 
            array (
                'id' => 203,
                'document_id' => 18416,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 288,
                'creation' => 1,
                'created_at' => '2018-04-20 10:44:40',
                'updated_at' => '2018-04-20 10:44:40',
                'deleted_at' => NULL,
            ),
            202 => 
            array (
                'id' => 204,
                'document_id' => 13414,
                'unit_teamwork_type_id' => 2,
                'ministry_id' => 3,
                'creation' => 1,
                'created_at' => '2018-04-20 10:54:36',
                'updated_at' => '2018-04-20 10:54:36',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}